# Generated by Django 4.0.2 on 2022-02-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=80, unique=True)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
