# Generated by Django 4.0.2 on 2022-02-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_doc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalDoc',
            new_name='Users',
        ),
    ]
